POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzU2NzYxMTQyLCJ1c2VySWQiOjF9.z_Uo78J96r4NNPqrfvDJYqGKec9MPldQnIIA2gAs92s

{
    "title":"Test Event 3",
    "description":"a test event to test",
    "location":"somewhere in vs studios",
    "datetime":"2025-08-29T14:00:00.000Z"
}